const data = {
    products: [
      {
        _id: '1',
        name: 'Shiva Canvas',
        category: 'Paintings',
        image: '/images/shiva_canvas.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Charcoal Drawing',
        category: 'Paintings',
        image: '/images/lotus_charcoal.jpg',
        price: 100,
        countInStock: 20,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Perspective Art',
        category: 'Paintings',
        image: '/images/perspective.jpg',
        price: 220,
        countInStock: 0,
        brand: 'Lacoste',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Doodle Art',
        category: 'Paintings',
        image: '/images/mask_zentangle.jpg',
        price: 78,
        countInStock: 15,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Mandala Art',
        category: 'Paintings',
        image: '/images/moon_doodle.jpg',
        price: 65,
        countInStock: 5,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Flower Charcoal',
        category: 'Paintings',
        image: '/images/flower_charcoal.jpg',
        price: 139,
        countInStock: 12,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;